# Generated by Django 3.2.8 on 2021-11-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
