# Generated by Django 3.2.8 on 2021-10-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('year_model', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('variant', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
